### ISSUE TITLE
Cannot read property 'resumeWithUrl' of undefined

### ISSUE THREAD

**Issue by panagulis72** [alexziskind1/nativescript-oauth2#105]
Hi,
I'm using nativescript-oauth2 for Angular+Nativescript app, and I'm handling urls with nativescript-urlhandler.
When I tap on a link and I choose to open with my app, I have the following error in console:  
`cannot read "resumeWithUrl" of undefined`

Debugging it I found that the error comes from delegate.android.js file in this line:
`TnsOAuthClientAppDelegate._client.resumeWithUrl(url);`

TnsOAuthClientAppDelegate exists but _client is null.

I resolved adding a simple if condition:
`        if (TnsOAuthClientAppDelegate._client) {
            TnsOAuthClientAppDelegate._client.resumeWithUrl(url);
        }`

Package versions:
"nativescript-fingerprint-auth": "^7.0.2"
"nativescript-urlhandler": "^1.3.0"
 "tns-core-modules": "6.0.1"

**Comment by keithgulbro** [comment]
@alexziskind1 This is a legitimate issue & @panagulis72 has proposed a valid solution that is verified to circumvent the app crashing. If I created a pull request with this fix could we merge it in?

**Comment by alexziskind1** [comment]
Hey Keith,
I’m looking for collaborators that can have a more active part in maintaining this plugin. You are pretty active here, so would you like to collaborate?
Right now all the demo apps need to be updated and the plugin needs to be tested in core, angular, and Vue.

**Comment by keithgulbro** [comment]
Hi @alexziskind1,

Yes, I could certainly provide a PR for the VueJS demo's. It will likely take me a week or so to complete. 

I'd also like to submit a PR for this update to the android.delegate.js file to resolve the `resumeWithUrl` bug presented inside this issue.

Thanks!

**Comment by kelf47** [comment]
Hi, you should add the same fix in Intent.ACTION_VIEW part. I'm gettings the same error when coming from deep link.
