### ISSUE TITLE
Receiving 401 Unauthorized when sending any request to backend

### ISSUE THREAD

**Issue by funder7** [alexziskind1/nativescript-oauth2#112]
### Which platform(s) does your issue occur on?
- Android 
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.5.0
- Cross-platform modules: 6.5.1
- Runtime(s): 6.5.0 (both)
- Plugin(s): 
```
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "^2.3.3",
    "core-js": "^2.6.9",
    "moment": "^2.24.0",
    "nativescript-angular": "^8.21.0",
    "nativescript-google-maps-sdk": "^2.9.1",
    "nativescript-oauth2": "^2.4.0",
    "nativescript-ui-dataform": "^6.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^6.5.4",
    "tns-core-modules": "^6.5.1",
    "tslib": "^1.11.1",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.0",
    "@angular/cli": "~8.3.0",
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "^1.0.0",
    "@nativescript/tslint-rules": "^0.0.5",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.9.5",
    "codelyzer": "^5.2.2",
    "husky": "^4.2.3",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "lint-staged": "^10.1.1",
    "nativescript-dev-webpack": "^1.5.1",
    "node-sass": "^4.7.1",
    "protractor": "~5.4.0",
    "tns-platform-declarations": "^6.5.1",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3",
    "webpack-cli": "^3.3.11"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
I've got a backend app generated with jhipster, which runs with Keycloak server. Everything works properly when using the provided Angular app, so I know that the environment is ok, at least for a web session. 

My Nativescript project is quite simple, I'm an inital stage. There's a LoginComponent which calls the AuthService, and I've managed to login successfully. 
After logging in, I've got the `idToken`, `accessToken` and `refreshToken`. 
So with an HttpInterceptor, I'm adding the `accessToken` inside of the GET request which I'm trying to do, directed to the API server. 
Unfortunately, I receive a 401 Unauthorized status in the response, and I don't know why it happens.

 My guess, by decoding the token, is that the "iss" property (issuer right?), points to 10.0.2.2, the emulator IP shortcut, which requests the tokens during the login. So when it sends a request with this issuer as the IP, maybe the Authorization Server fails, because it's setup on localhost/127.0.0.1, instead of 10.0.2.2 ? It's just my last bullet, I'm really out of ideas. 

I'm thinking also at a problem in the AuthServer configuration, but actually I've managed to authorize and make a call to the APIs with Postman.. So, I don't know. 

### Is there any code involved? 

This is the Custom provider, that I've configured for Keycloak: 
```
export class TnsOaProviderKeycloak implements TnsOaProvider {
    options: TnsOaProviderOptions;
    providerType                     = 'keycloakProvider';
    authority                        = 'http://10.0.2.2:9080/auth/realms/potpot/protocol/openid-connect';
    tokenEndpointBase                = 'http://10.0.2.2:9080/auth/realms/potpot/protocol/openid-connect';
    authorizeEndpoint                = '/auth';
    tokenEndpoint                    = '/token';
    revokeEndpoint                   = '/logout';
    cookieDomains                    = [ 'localhost', '10.0.2.2' ];

    constructor(options: TnsOaUnsafeProviderOptions) {
        this.options = options;
    }

    parseTokenResult(jsonData): ITnsOAuthTokenResult {
        return jsonData;
    }
}
```

authority & tokenEndpointBase are the same, I'm seeing this now, could be that be another reason? 

And the Provider's Options object:
```
const keycloakServerProviderOptions: TnsOaUnsafeProviderOptions = {
        openIdSupport: 'oid-none',
        clientId: 'ns-app',
        clientSecret: 'be651cd5-xxxxx-40d0-xxxxx-619d255b306e',
        // urlScheme: 'it.xxxx.xxxx.nsapp',
        redirectUri: 'it.xxxx.xxxxx.nsapp://auth',
        scopes: ['openid', 'jhipster', 'profile', 'email', 'offline_access'] 
    };
```

I know that this is not properly an issue, but I'm a newbie with this protocol, and sincerly....my brain is frying!  
I've tried to find the plugin author email with no luck. 

Thanks

**Comment by f-ricchiuto** [comment]
After doing some debugging, the problem seems related to the issuer stored inside of the token... it doesn't match with the one configured with my API server, that's due to the emulator network configuration. I can reach the authorization server on the host machine by using the 10.0.2.2 ip. But the API server reaches the Authorization server on localhost(127.0.0.1). 

Any hint on how to fix this?

**Comment by funder7** [comment]
Fixed by using docker network ip:

```
export class TnsOaProviderKeycloak implements TnsOaProvider {
    options: TnsOaProviderOptions;
    providerType                     = 'keycloakProvider';
    authority                        = 'http://172.17.0.1:9080/auth/realms/jhipster/protocol/openid-connect';
    tokenEndpointBase                = 'http://172.17.0.1:9080/auth/realms/jhipster/protocol/openid-connect';
    authorizeEndpoint                = '/auth';
    tokenEndpoint                    = '/token';
    revokeEndpoint                   = '/logout';
    cookieDomains                    = [ 'localhost', '172.17.0.1' ];


    constructor(options: TnsOaUnsafeProviderOptions) {
        this.options = options;
    }

    parseTokenResult(jsonData): ITnsOAuthTokenResult {
        return jsonData;
    }
}
```
