### ISSUE TITLE
Nativescript ng router issue

### ISSUE THREAD

**Issue by Ingi91** [alexziskind1/nativescript-oauth2#13]
Hi!

Thanks for the plugin, it works as expected but I can't redirect to another page on token result:

 this.authService
      .tnsOauthLogin("facebook")
      .then((result: ITnsOAuthTokenResult) => {
        console.log("back to app component with token" + result.accessToken);
       **this.routerextension.navigate(["/home"]);**
});

**Comment by alexziskind1** [comment]
Hi. Are you getting an access token back?

**Comment by Ingi91** [comment]
> 
> 
> Hi. Are you getting an access token back?

Thanks for reply
I get the token back, but when I try to redirect to another page with RouterExtensions it calls the ngOnInit but doesnt refresh the view

**Comment by alexziskind1** [comment]
That sounds like an issue with the ng router and not with the nativescript-oauth2 plugin. Since you're getting the token back, this plugin is doing what it's supposed to do. Navigating to a different component is not something this plugin is supposed to do.

**Comment by luchitod86** [comment]
> > Hi. Are you getting an access token back?
> 
> Thanks for reply
> I get the token back, but when I try to redirect to another page with RouterExtensions it calls the ngOnInit but doesnt refresh the view

Hi, i've the same problem. Could you solve it? 
I tried using ngZone, but it didn't work
Thanks

**Comment by s0l4r** [comment]
I have the exact same issue, trying to navigate after successful login using:
`this.routerextension.navigate(["/home"]); `

After login is successful, the router navigate is run but nothing happens and I am stuck at the login screen. Can this be related to using frames or pages? I am not sure how this works yet, but I will post any findings here.

**Comment by Ingi91** [comment]
> 
> 
> I have the exact same issue, trying to navigate after successful login using:
> `this.routerextension.navigate(["/home"]); `
> 
> After login is successful, the router navigate is run but nothing happens and I am stuck at the login screen. Can this be related to using frames or pages? I am not sure how this works yet, but I will post any findings here.

I know this is not the best solution but I temporarily solved using a timeout on ngOnInit():

        setTimeout(() => {
            let token = appSettings.getString("token",null);
            if(token){              
               this.router.navigate(["/home"]);
            }
        }, 2000);

**Comment by s0l4r** [comment]
> I know this is not the best solution but I temporarily solved using a timeout on ngOnInit():
> 
> ```
>     setTimeout(() => {
>         let token = appSettings.getString("token",null);
>         if(token){              
>            this.router.navigate(["/home"]);
>         }
>     }, 2000);
> ```

Works for me too.

**Comment by marcosnc08** [comment]
Hi! 

I'm Having the exact same issue, I added the setTimeOut() on my home.component.ts to redirect to home if token is present. 

this.router.navigate(["/home"]) is executing but the app keeps stuck at the login screen.

Can anyone give more details? or post the complete code?

Thanks!

**Comment by kokosky93** [comment]
same problem here

**Comment by rafaellyra** [comment]
I think that your problem is related to the fact that the lifecycle events from Angular don't really work exactly the same way in a Nativescript application, that is due to the fact that sometimes Nativescript will decide not to destroy your component but it will just load another "activity" and keep the activity that runs your component "silent" when that other activity gets closed your activity just "wakes up" so there is not always an `ngOnit` call when your login component is rendered.

The way you can overcome that is to listen to the `page.on('navigatingTo') event in addition to ngOnInit:

```
constructor(
  private page: Page
) {
 ngOnInit(): void {
    this.whatShouldHappenOnInit()
    this.page.on('navigatingTo', this.whatShouldHappenOnInit.bind(this)) // you can replace the bind with your preferred syntax
 }
  whatShouldHappenOnInit(): any{
 }
}
```
