### ISSUE TITLE
oauth2 plugin breaks when used together with firebase plugin after NS7 migration

### ISSUE THREAD

**Issue by cjohn001** [alexziskind1/nativescript-oauth2#135]
When using the firebase plugin together with the oauth2 plugin, the app crashes with the attached error.

@NathanWalker : I just tried to initialize the firebase and oauth plugins sequentially but this does not help. I also realized that the app crashes when I do not call firebase.init at all. It might be that the firebase plugin initializes itself once the plugin is loaded? Unfortunately I have not found the github sources of the firebase plugin you showed.

Please note, the bug I mentioned in https://github.com/alexziskind1/nativescript-oauth2/issues/134#issue-702707318 is a different one. There only the namespace for a function call was missing. For the issue here it would be best to look into the example sources I have provided

***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught TypeError: this.handleIncomingUrl is not a function
at
TnsOAuthClientAppDelegate.applicationOpenURLOptions(file: node_modules/nativescript-oauth2-ext/delegate/index.ios.js:14:0)
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught TypeError: this.handleIncomingUrl is not a function
at
TnsOAuthClientAppDelegate.applicationOpenURLOptions(file: node_modules/nativescript-oauth2-ext/delegate/index.ios.js:14:0)
', reason: '(null)'
*** First throw call stack:
(
0   CoreFoundation                      0x0000000115150e6e __exceptionPreprocess + 350
1   libobjc.A.dylib                     0x0000000114fbc9b2 objc_exception_throw + 48
2   NativeScript                        0x0000000110a302b4 _ZN3tns21NativeScriptException15OnUncaughtErrorEN2v85LocalINS1_7MessageEEENS2_INS1_5ValueEEE + 882
3   NativeScript                        0x0000000110e5d668 _ZN2v88internal14MessageHandler25ReportMessageNoExceptionsEPNS0_7IsolateEPKNS0_15MessageLocationENS0_6HandleINS0_6ObjectEEENS_5LocalINS_5ValueEEE + 344
4   NativeScript                        0x0000000110e5d4c9 _ZN2v88internal14MessageHandler13ReportMessageEPNS0_7IsolateEPKNS0_15MessageLocationENS0_6HandleINS0_15JSMessageObjectEEE<…>

These issues are very likely related and can be closed once this one is fixed:

https://github.com/alexziskind1/nativescript-oauth2/issues/113#issuecomment-651893514
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/1629

**Comment by cjohn001** [comment]
Hello @NathanWalker ,
the pr https://github.com/alexziskind1/nativescript-oauth2/pull/109 indeed fixed it. Thanks for the directions.

**Comment by cjohn001** [comment]
I unfortunately have too much changes in my copy of the sources in order to create a new pr. If one needs to apply the fix he can simply replace the 3 files in the delegate folder with those in the attached archive

[Archiv.zip](https://github.com/alexziskind1/nativescript-oauth2/files/5279509/Archiv.zip)

and change the line of code in oauth.ts according to the old pr

https://github.com/alexziskind1/nativescript-oauth2/pull/109/files

**Comment by NathanWalker** [comment]
Excellent thanks for letting us know @cjohn001 - we'll make the modifications here to allow delegate's from other plugins to all play together.

**Comment by cjohn001** [comment]
> Excellent thanks for letting us know @cjohn001 - we'll make the modifications here to allow delegate's from other plugins to all play together.

Thank you very much for your help, I would have probably never found the issue as it was absolutely unclear to me that the SafariViewController is a single instance shared between plugins.

**Comment by OvidiuGuta** [comment]
Hi @cjohn001. I have this same problem right now with my app and I was wandering if this fix was released in a version of this plugin on npm. I have updated the @nativesript/firebase plugin to the latest and I have v3.0.1 of nativescript-oauth2 and I still have the same problem.

Anything else I might be missing?

**Comment by cjohn001** [comment]
> Hi @cjohn001. I have this same problem right now with my app and I was wandering if this fix was released in a version of this plugin on npm. I have updated the @nativesript/firebase plugin to the latest and I have v3.0.1 of nativescript-oauth2 and I still have the same problem.
> 
> Anything else I might be missing?

Hello @OvidiuGuta, I assume it was not fixed yet, but I am not using this plugin anymore.
