### ISSUE TITLE
Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy.

### ISSUE THREAD

**Issue by juniorschen** [alexziskind1/nativescript-oauth2#152]
I'm using hydra and I have the following problem: Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy.

![image](https://user-images.githubusercontent.com/46031261/109529007-099d8a00-7a94-11eb-99c9-a69c6216d9d4.png)

I noticed that you have as hardcode the query state with "abcd"

**Comment by juniorschen** [comment]
correction of my side: 
![image](https://user-images.githubusercontent.com/46031261/109530162-31d9b880-7a95-11eb-94e9-7837e576b69b.png)

**Comment by BBazard** [comment]
If you use PKCE (which you should), state doesn't matter.

If you don't use PKCE, state needs to be a nonce, not just a fixed string, otherwise you will be open to cross-site request forgery attacks.
