### ISSUE TITLE
loginWithCompletion not always returning

### ISSUE THREAD

**Issue by eduardocalixtokorp** [alexziskind1/nativescript-oauth2#155]
### Which platform(s) does your issue occur on?
- Both iOS/Android/ emulators and real devices

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.1.2
- Plugin(s): 
```json
"dependencies": {
    "@angular/animations": "~10.1.0",
    "@angular/common": "~10.1.0",
    "@angular/compiler": "~10.1.0",
    "@angular/core": "~10.1.0",
    "@angular/forms": "~10.1.0",
    "@angular/platform-browser": "~10.1.0",
    "@angular/platform-browser-dynamic": "~10.1.0",
    "@angular/router": "~10.1.0",
    "@danvick/ngx-translate-nativescript-loader": "^3.0.0",
    "@nativescript-community/sentry": "^2.0.8",
    "@nativescript-community/ui-pager": "13.0.0-alpha.14",
    "@nativescript/angular": "10.1.7",
    "@nativescript/core": "7.0.13",
    "@nativescript/datetimepicker": "^2.0.4",
    "@nativescript/theme": "~2.3.0",
    "@nativescript/unit-test-runner": "^1.0.2",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@nstudio/nativescript-cardview": "^2.0.0",
    "@nstudio/nativescript-loading-indicator": "^4.0.0",
    "angular2-uuid": "^1.1.1",
    "http-mockserver": "^2.2.2",
    "jwt-decode": "^3.1.2",
    "nativescript-barcodescanner": "^3.4.2",
    "nativescript-oauth2": "^3.0.3",
    "nativescript-speech-recognition": "^1.5.0",
    "nativescript-sqlite": "^2.6.3",
    "nativescript-toast": "^2.0.0",
    "nativescript-toasty-ns-7": "^14.0.0",
    "nativescript-ui-calendar": "^7.0.2",
    "nativescript-ui-chart": "^8.0.2",
    "nativescript-ui-listview": "9.0.4",
    "nativescript-ui-sidedrawer": "9.0.2",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~10.1.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/ios": "7.0.6",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "@ngtools/webpack": "~10.1.0",
    "@types/jasmine": "3.5.14",
    "@types/node": "~10.12.18",
    "jasmine": "~3.3.1",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "json-server": "^0.16.3",
    "karma": "5.2.3",
    "karma-jasmine": "4.0.1",
    "karma-nativescript-launcher": "0.4.0",
    "karma-webpack": "3.0.5",
    "nativescript-dev-appium": "6.1.3",
    "typescript": "~3.9.0"
  }
```
- Used Oauth Server: [Ory Hydra](https://www.ory.sh/hydra/docs/)
- Authentication Flow: Authorization Code + pkce 

### Please, tell us how to recreate the issue in as much detail as possible. 

1. Setup oauth server / client
2. Edit nativescript/oauth2 TnsOaProvider.options.scopes with an invalid scope
3. Call loginWithCompletion method
4. An error will occour internally in oauth server, returning to the following url: ```<REDIRECT_URL>?error=InvalidScopeRequested&errorDescription='notValidScope'+is+not+a+valid+scope```

Following the step by step process above, the completition function is never called back.
PS: Notice that error is returned to the correct REDIRECT_URL registered, but it does not contain a valid response (in my case, using authorization_code + pkce flow one)

### Is there any code involved? 
```ts
this.oauthClient.loginWithCompletion((tokenResult: ITnsOAuthTokenResult, error: Error | string) => {
    console.log('this line is not called when error is returned from oauth server');
}
```

**Comment by juniorschen** [comment]
Same issue @alexziskind1

**Comment by meeshkabob** [comment]
I'm seeing a similar behavior in `logoutWithCompletion`.

If the refresh token saved to the `nativescript-oauth2` client object is past its expiration date at the time that `logoutWithCompletion` is called, then the `completion` function passed to it is never called.

```
"nativescript-oauth2": "^3.0.3",
"@nativescript/angular": "10.1.7",
"@nativescript/core": "7.1.3",
"@nativescript/localize": "^5.0.4",
"@nativescript/android": "7.0.1",
"@nativescript/ios": "7.2.0",
"@nativescript/types": "^7.2.0",
"typescript": "~3.9.0"
```

**Comment by eduardocalixtokorp** [comment]
This problem happens when resumeWithUrl returns false
![image](https://user-images.githubusercontent.com/74939253/119846065-30772b00-bee0-11eb-9fc6-23698179535d.png)

**Comment by facetious** [comment]
@eduardocalixtokorp Does this still occur in 3.0.5?

**Comment by eduardocalixtokorp** [comment]
I'll test it later, but it probably should work because a override this method locally for a similar solution of 3.0.5 version.
I'm closing this issue for now. Thank you @facetious
