### ISSUE TITLE
Microsoft loggin problem

### ISSUE THREAD

**Issue by meztliger** [alexziskind1/nativescript-oauth2#18]
- CLI: 5.1.0
- Cross-platform modules: Android 4.2.0(check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)

- Plugin(s):     "@angular/animations": "5.2.0",
    "@angular/common": "5.2.0",
    "@angular/compiler": "5.2.0",
    "@angular/core": "5.2.0",
    "@angular/forms": "5.2.0",
    "@angular/http": "5.2.0",
    "@angular/platform-browser": "5.2.0",
    "@angular/platform-browser-dynamic": "5.2.0",
    "@angular/router": "5.2.0",
    "base-64": "^0.1.0",
    "nativescript-angular": "~5.2.0",
    "nativescript-bitmap-factory": "^1.7.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-clipboard": "^1.1.7",
    "nativescript-exit": "^1.0.1",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-oauth2": "^1.3.1",
    "nativescript-plugin-firebase": "^5.3.1",
    "nativescript-pro-ui": "~3.3.0",
    "nativescript-push-notifications": "^1.1.4",
    "nativescript-ripple": "^2.1.0",
    "nativescript-social-share": "github:moderateepheezy/nativescript-social-share#patch-1",
    "nativescript-sqlite": "^2.2.1",
    "nativescript-status-bar": "^1.1.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-uuid": "0.0.1",
    "nativescript-zxing": "^1.5.6",
    "reflect-metadata": "~0.1.10",
    "rxjs": "^5.5.11",
    "tns-core-modules": "^4.2.0",
    "tns-platform-declarations": "^5.1.2",
    "utf8": "^3.0.0",
    "zone.js": "^0.8.26"

"devDependencies": {
    "@angular/compiler-cli": "^5.2.0",
    "@ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "codelyzer": "~4.0.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "~1.3.5",
    "nativescript-dev-typescript": "~0.6.0",
    "nativescript-dev-webpack": "^0.9.2",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "tslint": "~5.8.0",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-sources": "~1.1.0"
  }

Trying to log in with microsoft aacount quen click Yes on Acces Infoscreen, a message apears "Safari cannot open the page because the  address is invalid".
The invalid address is urn:ietf:wg:oauth:2.0:oob from the redirect uri property from TnsOaProviderOptionsMicrosoft

**Comment by alexziskind1** [comment]
If you are using microsoft and configuring `openIdSupport` to `oid-full` then you can't use `urn:ietf:wg:oauth:2.0:oob` as your redirect uri. You need a custom scheme set up with a custom redirect uri that matches. Please refer to the [demo application](https://github.com/alexziskind1/nativescript-oauth2/tree/master/demo-angular).
