### ISSUE TITLE
[Android] Plugin incompatible with newer Gradle versions

### ISSUE THREAD

**Issue by timoschlueter** [alexziskind1/nativescript-oauth2#186]
Hi @alexziskind1, I am trying to use this plugin on Android and noticed that it is not compatible with newer versions of Gradle since it uses the deprecated "compile()"-Method in the `include.gradle` file: https://github.com/alexziskind1/nativescript-oauth2/blob/d9f6a1861dcedc4e8d2ad34be8a8ae1bdb5680e8/src/platforms/android/include.gradle#L2-L3
`compile` should be changed to `api` to make the plugin compatible with Gradle 7+.
I tested this by manually changing the file and it works fine.

Any chance of publishing a new version of this awesome plugin? :)

**Comment by alexziskind1** [comment]
hi @timoschlueter yes, Im planning an update this week which will include some other folks' PRs. since you've already done the work, could you submit a Pull Request and I'll be sure to include that in the release?
cheers

**Comment by timoschlueter** [comment]
sure @alexziskind1! i have opened a PR. :)
