### ISSUE TITLE
iOS Google signIn wont work

### ISSUE THREAD

**Issue by marvynorourkeTT** [alexziskind1/nativescript-oauth2#189]
### Which platform(s) does your issue occur on?
- iOS
- iOS: 13.5
- emulator or device.

### Please, provide the following version numbers that your issue occurs with:

- CLI:8.2.3-next-03-23-2022-2029350027
- Plugin(s): "dependencies": {
    "@nativescript-community/ui-material-bottom-navigation": "^6.2.2",
    "@nativescript/core": "^8.2.1",
    "@nativescript/facebook": "^1.0.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/google-signin": "^1.0.0",
    "@nativescript/imagepicker": "^1.0.5",
    "@nativescript/payments": "^1.0.4",
    "@nativescript/theme": "~3.0.1",
    "@nstudio/nativescript-carousel": "^8.0.2",
    "axios": "^0.24.0",
    "base-64": "^1.0.0",
    "nativescript-apple-sign-in": "^2.0.0",
    "nativescript-download-progress": "^1.4.3",
    "nativescript-image-filters": "^4.0.0",
    "nativescript-oauth2": "^3.0.7",
    "rxjs": "^7.4.0",
    "sass": "^1.43.5",
    "typescript": "^4.5.2",
    "utf8": "^3.0.0"
  },
  "devDependencies": {
    "@nativescript/android": "8.1.1",
    "@nativescript/ios": "~8.2.2",
    "@nativescript/webpack": "~5.0.0"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
Unable to open the Google service login page only on iOS, no error message is displayed and the loginWithCompletion function returns nothing and never completes. When I launch the application with xCode I get a small warning but nothing more.

The warning: 
 Warning: Attempt to present <SFSafariViewController: 0x7faa0e2cae00> on <UIViewControllerImpl: 0x7faa05c336c0> whose view is not in the window hierarchy!

### Is there any code involved? 

```
const googleProviderOptions = {
    openIdSupport: "oid-full",
    clientId: "xxxxxx.apps.googleusercontent.com",
    redirectUri: "com.googleusercontent.apps.xxxxxxx:/auth",
    urlScheme: "com.googleusercontent.apps.xxxxxx",
    scopes: ["email", "profile"],
  };
  return new providers.TnsOaProviderGoogle(googleProviderOptions);
```

**Comment by mreall** [comment]
@marvynorourkeTT Were you able to get it to work? I have a custom provider that works on Android, but won't open the browser when I tap the Sign In button on iOS.
