### ISSUE TITLE
Debug network with chrome devtools

### ISSUE THREAD

**Issue by s0l4r** [alexziskind1/nativescript-oauth2#19]
### Please, tell us how to recreate the issue in as much detail as possible. 

When starting the debug session either using TNS CLI or using NativeScript Sidekick, the debugger session starts but I cannot see any network requests at all. Does this plugin support network debugging? Looks like plugin authors need to support it, according to https://docs.nativescript.org/tooling/debugging/chrome-devtools#plugin-authors-guide

Or could this be related to the http client?
import { NativeScriptHttpClientModule } from "nativescript-angular/http-client";

### Which platform(s) does your issue occur on?
- iOS
- Both emulator and device. 

What type of device?
- iPhone 8 tested

### Please, provide the following version numbers that your issue occurs with:

- CLI: 
tns --version
5.1.1

- Cross-platform modules:
tns-core-modules@5.1.2

- Runtime(s): 
"tns-ios": { "version": "5.1.0" }

- Plugin(s):
"dependencies": {
        "@angular/animations": "~7.1.0",
        "@angular/common": "~7.1.0",
        "@angular/compiler": "~7.1.0",
        "@angular/core": "~7.1.0",
        "@angular/forms": "~7.1.0",
        "@angular/http": "~7.1.0",
        "@angular/platform-browser": "~7.1.0",
        "@angular/platform-browser-dynamic": "~7.1.0",
        "@angular/router": "~7.1.0",
        "nativescript-angular": "~7.1.0",
        "nativescript-oauth2": "^1.3.1",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-toast": "1.4.6",
        "nativescript-ui-listview": "5.1.1",
        "nativescript-ui-sidedrawer": "5.1.0",
        "reflect-metadata": "~0.1.10",
        "rxjs": "~6.3.0",
        "rxjs-compat": "^6.3.3",
        "tns-core-modules": "~5.1.0",
        "zone.js": "~0.8.18"
    },
    "devDependencies": {
        "@nativescript/schematics": "~0.5.0",
        "nativescript-dev-typescript": "~0.7.0",
        "nativescript-dev-webpack": "~0.19.0",
        "@angular/compiler-cli": "~7.1.0",
        "@ngtools/webpack": "~7.1.0"
    },

### Is there any code involved? 
Oauth2 plugin code is executing networks calls and it is working, but no calls are visible in Chrome devtools.

**Comment by alexziskind1** [comment]
You'll only see network traffic in the Chrome debugger from http requests made in the application. This is the POST to the auth server for the token, not the login itself. The login either uses the webview or the system browser, which will not show http requests/responses in the debugger.
