### ISSUE TITLE
How to just continue login using facebook account without provide email and password?

### ISSUE THREAD

**Issue by LSmint** [alexziskind1/nativescript-oauth2#24]
If my facebook app already login in device, how to just click continue using the current login id instead of go through the login screen with email and password input?

**Comment by dronowar** [comment]
+1

**Comment by alexziskind1** [comment]
The cookies inside webview are not shared with the cookies of the system browser. Facebook login in the example provided uses webview. An implementation of system browser login for Facebook will be needed in order to maintain logged in state.
