### ISSUE TITLE
Sintax problem in vue-cli

### ISSUE THREAD

**Issue by asiermusa** [alexziskind1/nativescript-oauth2#31]
Hi,

I have some problems with the sintax (this 2 lines) with the vue-cli:

**Unexpected token, expected "{"**

```
function configureOAuthProviderGoogle(): TnsOaProvider {
  const googleProviderOptions: TnsOaProviderOptionsGoogle = {
```

Thanks

**Comment by wa05** [comment]
Try removing the Typescript type : TnsOaProvider
