### ISSUE TITLE
Can't use other tenant then common for the login.microsoftonline.com

### ISSUE THREAD

**Issue by MrFritmand** [alexziskind1/nativescript-oauth2#32]
### Make sure to check the demo app(s) for sample usage 
Does not seem like there is a sample for this.
### Make sure to check the existing issues in this repository 
The issue does not seem to be present at this time.
### If the demo apps cannot help and there is no issue for your problem, tell us about it
I want to use for example "https://login.microsoftonline.com/contoso.onmicrosoft.com" instead of "https://login.microsoftonline.com/common" as login URL but if i try to change it in the node_modules/nativescript-oauth2/providers/providers.js the app just closes when clicking sign in.

### Which platform(s) does your issue occur on?
- Android
- Android Pie 9.0 
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.4
- Cross-platform modules: 5.2.2
- Runtime(s): tns-android = 5.2.1
- Plugin(s): nativescript-oauth2: ^1.4.1,

### Please, tell us how to recreate the issue in as much detail as possible. 
In the node_modules/nativescript-oauth2/providers/providers.js file edit the "https://login.microsoftonline.com/common" to "https://login.microsoftonline.com/{tenant}"

**Comment by alexziskind1** [comment]
You can do this by implementing a custom provider. The MS provider that is included only points at `common`. Take a look at the docs on implementing a custom provider to get to a specific tenant

**Comment by MrFritmand** [comment]
Made a custom provider and it works on IOS but on Android, it just closes the app when clicking login.

**Code:**
[https://pastebin.com/TSynGvJw](url)

**Comment by MrFritmand** [comment]
@alexziskind1 This is the URL I'm getting

`https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize?client_id={clientId}&response_type=code&redirect_uri=msal{clientId}%3A%2F%2Fauth&scope=openid%20profile%20Calendars.ReadWrite.Shared%20offline_access%20User.ReadBasic.All&response_mode=query&state=abcd`

**Comment by MrFritmand** [comment]
@alexziskind1 
I have done some testing and I can conclude that it only happens on Android 9.0.
It's because before(> 24 April 2019) you would be prompt to select an account even if you only were logged in to one but now(< 25 April 2019) if only one account is logged in it will continue with that account without your consent and crash but if you open the app again from the recent applications menu the app is now logged in.
But if you are logged in to more than one account it will prompt you to choose and not crash or you are not logged in at all and it will ask you to log in and again not crash.

This behavior is the same on Android 8.1 or later but the app does not crash.
So it would seem that the issue lays at Microsoft.

**Comment by MrFritmand** [comment]
@alexziskind1 
temp fix in node_modules/nativescript-oauth2/tns-oauth-utils.js i add a ekstra 
`params"prompt" = "select_account";`

**Comment by MrFritmand** [comment]
Ended up using the new customQueryParams and set `prompt: "select_account"`
