### ISSUE TITLE
Expose Webview or create Webview Events to hook into

### ISSUE THREAD

**Issue by Eonfuzz** [alexziskind1/nativescript-oauth2#33]
Exposing the webview is needed, as it lets us programmatically prefill usernames, add our own custom ui (Such as loading screens) and also override default navigation.

**Comment by alexziskind1** [comment]
Providing a custom UI goes against the Oauth2 spec. Your Authorization server should provide the UI.

**Comment by Eonfuzz** [comment]
What about adding a native actionbar to the page? Or intercepting navigation events to have it better mesh with angular routing?
