### ISSUE TITLE
Unable to login with the Microsoft provider

### ISSUE THREAD

**Issue by homesar** [alexziskind1/nativescript-oauth2#34]
### Which platform(s) does your issue occur on?
-Andorid

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.4
- Cross-platform modules: 5.2.2
- Runtime(s): 5.2.0
- Plugin(s): "dependencies": {
        "@angular/animations": "~7.2.0",
        "@angular/common": "~7.2.0",
        "@angular/compiler": "~7.2.0",
        "@angular/core": "~7.2.0",
        "@angular/forms": "~7.2.0",
        "@angular/http": "~7.2.0",
        "@angular/platform-browser": "~7.2.0",
        "@angular/platform-browser-dynamic": "~7.2.0",
        "@angular/router": "~7.2.0",
        "nativescript-angular": "~7.2.1",
        "nativescript-oauth2": "^1.4.1",
        "nativescript-theme-core": "~1.0.4",
        "reflect-metadata": "~0.1.12",
        "rxjs": "~6.3.0",
        "tns-core-modules": "~5.2.0",
        "zone.js": "~0.8.26"
    },
    "devDependencies": {
        "@angular/compiler-cli": "~7.1.0",
        "@nativescript/schematics": "~0.5.0",
        "@ngtools/webpack": "~7.1.0",
        "nativescript-dev-typescript": "~0.8.0",
        "nativescript-dev-webpack": "~0.20.0"
    },
### Please, tell us how to recreate the issue in as much detail as possible. 
git clone https://github.com/alexziskind1/nativescript-oauth2.git

Modify demo-angular app\src\app.component.ts, line 19 to read: .tnsOauthLogin("microsoft")
Build and deploy to android device.
Hit the login button.
Sign in with a microsoft account.  I used a live account.
The app will not proceed beyond the permissions acceptance screen.  See screenshot.

I first tried in my own app with my own client id and callback urls, but I received the same issue.  So I pulled the repo to try it with the demo app and it is repeatable there.

![Screenshot_20190329-152335](https://user-images.githubusercontent.com/14047923/55258185-7f5da300-5238-11e9-8e71-047f5d174a87.png)

**Comment by isojtouano** [comment]
I am having the same issue, does anyone know how to fix this? Thanks

**Comment by isojtouano** [comment]
I have found the solution to this problem. You just have to add one more <data> tag inside your intent-filter in your Android Manifest file, do it like so: 
`<data android:scheme="MICROSOFT_URL_SCHEME_HERE"/>`

**Comment by alexziskind1** [comment]
Thanks
