### ISSUE TITLE
Is there PKCE support?

### ISSUE THREAD

**Issue by MitchZA** [alexziskind1/nativescript-oauth2#36]
Thank you for a great plugin! 

Question question, does this plugin support "Authorization Code Flow with PKCE"? I have noticed that the class TnsOAuthState does have a codeVerifier but it is set to '' during the object creation.

Is there maybe sample code that shows the use of PKCE?

Otherwise, would it be possible to have an option to pass in custom parameters?

**Comment by alexziskind1** [comment]
The infrastructure is there to support it, but the crypto functions just need to be added. Care to submit a PR?
