### ISSUE TITLE
Support for multiple flows

### ISSUE THREAD

**Issue by marconline** [alexziskind1/nativescript-oauth2#44]
Hi and thanks for this package.

I've created a custom provider for our auth server that requires, for this kind of application, a Hybrid (or Implicit) flow. This means that the token is received as fragment in the redirect url (custom url scheme). 

We succeeded in letting this work by overriding the **getAuthUrlStr()** method. The problem is that when we get the redirection back, it seems that the loginWithCompletion callback doesn't fire.

Any workaround? Thanks.

**Comment by alexziskind1** [comment]
Thanks for the comment @vincentpalita . That is exactly right. Here is a sample angular main.ts file where the plugin config is initialized BEFORE Angular's bootstrap process.
https://github.com/alexziskind1/nativescript-oauth2/blob/master/demo-angular/src/main.ts
