### ISSUE TITLE
Demo-vue fails on npm install

### ISSUE THREAD

**Issue by marcelopham** [alexziskind1/nativescript-oauth2#47]
### Which platform(s) does your issue occur on?
- iOS
- Device: iPhone 7 plus

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.4.0
- Cross-platform modules: node_modules directory is empty
- Runtime(s): tns-ios 5.2.0
- Plugin(s): 
  "dependencies": {
    "nativescript-vue": "2.0.2",
    "nativescript-oauth2": "file:../src",
    "tns-core-modules": "5.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "next",
    "nativescript-vue-template-compiler": "^2.0.2",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "terser-webpack-plugin": "^1.1.0",
    "vue-loader": "^15.2.6",
    "webpack": "^4.16.4",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.1.0"
  }
### Please, tell us how to recreate the issue in as much detail as possible. 
$ git clone https://github.com/alexziskind1/nativescript-oauth2.git
$ cd nativescript-oauth2/demo-vue
$ npm install 
WARN tar ENOENT: no such file or directory, open '/Users/marcelo/Documents/root/rings/nativescript-oauth2/demo-vue/node_modules/.staging/microevent.ts-899fbe76/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/marcelo/Documents/root/rings/nativescript-oauth2/demo-vue/node_modules/.staging/microevent.ts-899fbe76/.travis.yml'
WARN tar ENOENT: no such file or directory, open '/Users/marcelo/Documents/root/rings/nativescript-oauth2/demo-vue/node_modules/.staging/microevent.ts-899fbe76/LICENSE'
WARN tar ENOENT: no such file or directory, open '/Users/marcelo/Documents/root/rings/nativescript-oauth2/demo-vue/node_modules/.staging/microevent.ts-899fbe76/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/marcelo/Documents/root/rings/nativescript-oauth2/demo-vue/node_modules/.staging/microevent.ts-899fbe76/tsconfig.json'
WARN tar ENOENT: no such file or directory, open '/Users/marcelo/Documents/root/rings/nativescript-oauth2/demo-vue/node_modules/.staging/microevent.ts-899fbe76/tsconfig.test.json'
WARN tar ENOENT: no such file or directory, open '/Users/marcelo/Documents/root/rings/nativescript-oauth2/demo-vue/node_modules/.staging/microevent.ts-899fbe76/typings.json'
WARN tar ENOENT: no such file or directory, open '/Users/marcelo/Documents/root/rings/nativescript-oauth2/demo-vue/node_modules/.staging/microevent.ts-899fbe76/yarn.lock'
npm WARN ts-loader@5.4.5 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN demo-vue@1.0.0 No repository field.

npm ERR! path /Users/marcelo/Documents/root/rings/nativescript-oauth2/demo-vue/node_modules/.staging/nativescript-oauth2-a74cb9fb/node_modules/ansi-regex
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/marcelo/Documents/root/rings/nativescript-oauth2/demo-vue/node_modules/.staging/nativescript-oauth2-a74cb9fb/node_modules/ansi-regex' -> '/Users/marcelo/Documents/root/rings/nativescript-oauth2/demo-vue/node_modules/.staging/ansi-regex-dcbdd206'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

(then it freezes there)

### Is there any code involved? 
 - No - this is the clone of the repo

Thanks!!!

M

**Comment by alexziskind1** [comment]
Thanks M. 
The vue demo relies on the plugin being built. Please follow the plugin building instructions: https://docs.nativescript.org/plugins/building-plugins
