### ISSUE TITLE
Is  createFrameOnBootstrap: true necessary?

### ISSUE THREAD

**Issue by ahmadakra** [alexziskind1/nativescript-oauth2#5]
Dear Alex,

In the docs is says that for Angular projects the flag createFrameOnBootstrap must be set to `true`

`// main.ts
platformNativeScriptDynamic({ createFrameOnBootstrap: true }).bootstrapModule(
  AppModule
);`

I tried it without setting this flag and it still works just the same (using Google authentication). So what gives? What goes wrong if I don't set this flag?
The problem with setting the flag to `true` is that I need to use page-router-outlet since I am in a code sharing Angular project and I need to reuse the routing code and I still need the "back" button of Android to work as expected with the navigation.
When you set the above flag to `true` AND use page-router-outlet at the same time you end up with undesirable behavior such as two action bars:

![image](https://user-images.githubusercontent.com/43896758/48636559-500e6e00-e9dc-11e8-880e-b87210f6d8be.png)

So if I can get away without this flag, it would be great.

Best wishes

**Comment by alexziskind1** [comment]
If you are using `<page-router-outlet` then you don't need that setting. I've updated the docs. Thanks!
