### ISSUE TITLE
customDelegate

### ISSUE THREAD

**Issue by Carli0s** [alexziskind1/nativescript-oauth2#52]
I am developing with IOS.

The plugin is working fine for me, but I have a custom delegate and there is not working when i use this plugin.

In my delegate I have other configurations to the application, for example configuration for  login with twitter and here i put the code for the initialisation.

 I can see that the plugin "oauth2" is creating a delegate.

My question is if someone know if its posible to work the plugin and my delegate configuration..

Thanks

**Comment by saeb-panahifar** [comment]
Yes, Write

**Comment by saeb-panahifar** [comment]
```
function configureClientAuthAppDelegate(): void {
  applicationModule.ios.delegate = TnsOAuthClientAppDelegate;
}
```

**Comment by alexziskind1** [comment]
Delegate overwriting is currently an issue - thinking about a possible solution, but haven't come up with one yet. Let me know if you do

**Comment by b-ivanovic** [comment]
Why this issue is closed? Is it solved?

**Comment by b-ivanovic** [comment]
Why is this issue closed? Is it solved?
