### ISSUE TITLE
Demo-VueJs Error 

### ISSUE THREAD

**Issue by jaasaria** [alexziskind1/nativescript-oauth2#6]
Hi Alex!
First thank you for this plugin.  Bellow the following error I encountered.

### Make sure to check the demo app(s) for sample usage 
Yes and here the problem I encountered.

### Make sure to check the existing issues in this repository 
Yes

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

Upon checking your demo app, after npm install and command "tns run android --bundle" and error occured. Here's the screenshot of the error. 
https://ibb.co/fUtN4f

Also I have a question: Why under demo-vue folder, I dont see the imported "auth-service" file.
> var auth_service_1 = require("../auth-service");
Where is the file located? 

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?
Im using Windows 10

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

I dont add anything. All dependencies/devDep is the default one in your demo.

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
1.Download via zip
2. go to folder "demo-vue" then run "npm install" and "tns run android --bundle"

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.
No added code****

**Comment by alexziskind1** [comment]
The vue demo project was missing all the js files due to incorrect .gitignore settings. This was fixed. Please try again
