### ISSUE TITLE
ios, google login, vue, not redirect to app

### ISSUE THREAD

**Issue by adehuh** [alexziskind1/nativescript-oauth2#62]
Dear All,
I tried this module, but after success  login in google, just back to google.com,  not back to my app.

any miss in my configure ?

The sample here
https://github.com/adehuh/oauth-m2.git

```
<template>
     <StackLayout height="100%" width="100%">
   
<Button text="Login" class="btn btn-primary "  @tap="openLogin" />

  </StackLayout>
</template>

<script>
import { configureTnsOAuth } from "nativescript-oauth2";
import {
  TnsOaProvider,
  TnsOaProviderOptionsFacebook,
  TnsOaProviderFacebook,
  TnsOaProviderOptionsGoogle,
  TnsOaProviderGoogle,
  TnsOaProviderOptionsMicrosoft,
  TnsOaProviderMicrosoft
} from "nativescript-oauth2/providers";
import { TnsOAuthClient, ITnsOAuthTokenResult } from "nativescript-oauth2";
export default {
  components: {},
  mounted() {
    console.log(111111111111111111111111111);
    configureTnsOAuth([this.configureOAuthProviderGoogle()]);
    console.log(222222);
  },
  data() {
    return {};
  },
  methods: {
    openLogin() {
      console.log(">>>>>>>>");
      var providerType = "google"; //'google', 'facebook', 'microsoft',
      this.tnsOauthLogin(providerType);
    },
    tnsOauthLogin(providerType) {
     const client = new TnsOAuthClient(providerType);
      client.loginWithCompletion(function(tokenResult, error) {
        if (error) {
          console.error("back to main page with error: ");
          console.error(error);
        } else {
          console.log("back to main page with access token: ");
          console.log(tokenResult);
        }
      });
    },
    configureOAuthProviderGoogle() {
      const googleProviderOptions = {
        openIdSupport: "oid-full",
        clientId:
          "411282977902-35eeg8vsgorkgcq81v518b7u88quchbg.apps.googleusercontent.com",
        redirectUri: "com.googleusercontent.apps.411282977902-35eeg8vsgorkgcq81v518b7u88quchbg:/auth",// kay berhasil;
        //redirectUri: "http://localhost:9000/oauth2/authorization/oidc",
        urlScheme:
          "com.googleusercontent.apps.411282977902-35eeg8vsgorkgcq81v518b7u88quchbg",
        scopes: ["email"]
      };
      const googleProvider = new TnsOaProviderGoogle(googleProviderOptions);
      return googleProvider;
    }
  }
};
</script>
```

```
<key>CFBundleURLTypes</key>
    <array>
		<dict>
		<key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>CFBundleURLName</key>
            <string>org.nativescript.application</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.411282977902-35eeg8vsgorkgcq81v518b7u88quchbg</string>		
			</array>
		</dict>
    </array>
</dict>
</plist>
```
### Which platform(s) does your issue occur on?
- iOS 

Sincerely,
adehuh

**Comment by tayalakansh** [comment]
Facing same issue in android, google login with nativescript angular. Page getting redirected to just google.com instead of app.

**Comment by tayalakansh** [comment]
I had not added intent-filter property in my AndroidManifest.xml file. After adding it worked perfectly fine.

`<intent-filter>
				<action android:name="android.intent.action.VIEW"/>
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				
				<data android:path="/auth" android:scheme="com.googleusercontent.apps.xxxxxxx"/>
			</intent-filter>`

**Comment by alexziskind1** [comment]
Thanks for the update

**Comment by lsowmya** [comment]
Facing same issue in iOS 13,
No issue in Android or in iOS 12, Started facing issue in iOS 13 not navigating to my app. 
We have Two factor authorization after suspending and approving, when getting back to my app, its getting struck there..

Started facing issue with iOS13. Need suggestions.

Thanks in advance.

**Comment by AhmedAdelAtta** [comment]
> Hi,
> i have the same bug : not redirect to app but instead google main page.
> I use 2 devices : iOS & Android.
> on iOS, all working perfectly
> on Android, bug
> 
> I checked my AndroidManifest.xml, everything is ok :
> 
> ```
>  <intent-filter>
>                 <action android:name="android.intent.action.VIEW"/>
>                 <category android:name="android.intent.category.DEFAULT" />
>                 <category android:name="android.intent.category.BROWSABLE" />
>                 
>                 <data android:path="/auth" android:scheme="com.googleusercontent.apps.505059267680-j3dtql1b4jcnros6kgujc5f8u3107cai"/>
>             </intent-filter>
> ```
> 
> Maybe a breaking change ?

I have the same issue man with ios redirecting to google, can you please share with me what you did cause its driving me crazy!!
