### ISSUE TITLE
Not an issue but a sample with Okta

### ISSUE THREAD

**Issue by cyberbobjr** [alexziskind1/nativescript-oauth2#64]
Hi,
I don’t really know where to post this snippet, but i have made a sample of Nativescript-oauth2 with Okta platform :
https://github.com/cyberbobjr/okta-nativescript

Maybe if you can open the Wiki ?
Many thanks for your wonderfull job !
Regards

**Comment by alexziskind1** [comment]
That’s really great! Thanks! It may be a good one for wiki

**Comment by alexziskind1** [comment]
I've added the wiki page - thanks again
