### ISSUE TITLE
Can I connect Identity Server 4 with this plugin?

### ISSUE THREAD

**Issue by kerbooo** [alexziskind1/nativescript-oauth2#65]
Hello I am searching about 1 week. I am new about Identity Server and I did not understand clearly working mechanism about Identity Server.

Accutally I have developed a demo app with Xamarin for connecting to Identity Server 4 with using C# Oidc Client and I succesfully connected. But I need to develop a mobile demo app with NativeScript for comparing two platforms performance. I know to use Nativescript with Vue. I need really help. Because I do not have so much times.

My questions about "Can I connect Identity Server with this plugin or not". I have used below params when connect to Identitiy Server with Xamarin. I have examined your plugin but I did not find params as below.

```
var _OidcClientOptions = new OidcClientOptions
            {
                Authority = "https://auth.......",
                ClientId = "...........",
                ClientSecret = "..........",
                Scope = "openid profile email api",
                RedirectUri = "clients://callback",
                PostLogoutRedirectUri = "clients://callback",
            };
```

C# plugin URL is [here ](https://github.com/IdentityModel/IdentityModel.OidcClient)

Thank you very much in advance.

**Comment by JoshDSommer** [comment]
We use Identity Server 4 and this plugin. 

you want to create custom provider following the steps outlined in the readme with your config options. 

https://github.com/alexziskind1/nativescript-oauth2#creating-a-custom-provider

**Comment by kerbooo** [comment]
Hello @JoshDSommer 

Firstly thank you for your replay. I have added custom provider but I think my settings are wrong. Can you tell me what are the default settings of Identity Server 4 for below settings? 

Also customm provider sample is typescript. I have converted it because I am using Vue. 


```
export class TnsOaProviderMyCustomProvider {
    constructor(options) {
        this.openIdSupport = "oid-full";
        this.providerType = "my-custom";
        this.authority = "https://mydomain.com/";
        this.tokenEndpointBase = "https://mydomain.com/";
        this.authorizeEndpoint = "/connect/authorize";
        this.tokenEndpoint = "/connect/token";
        this.cookieDomains = ["mydomain.com"];
        this.options = options;
    }
    parseTokenResult(jsonData) {
        return jsonData;
    }
}
```

Last question more. How to get API after getting valid token? I mean which compenent or method use in your project?

**Comment by JoshDSommer** [comment]
everything you provided looks fine at first glance. there is still more you need to setup. I some difficulties getting the settings right between the server and the app. 

Fortunately I had found this example someone else did, https://github.com/Elrashid/nativescript-client-and-identity-server-sample. I hope that helps you.

**Comment by kerbooo** [comment]
Hello again.

I have achived to connect server but I am getting "invalid client" error. I
mean I can not show login screen. My Identity server is not test. It works
long time. I mean it is commercial structure.

I think I sould change identity server setting for achiving this error am I
right?

15 Eyl 2019 Paz 13:56 tarihinde Josh Sommer <notifications@github.com> şunu
yazdı:

**Comment by JoshDSommer** [comment]
@kerbooo I would double check you identity server settings. 

you can cross check that your settings with their discovery endpoint. 
http://docs.identityserver.io/en/latest/endpoints/discovery.html

hope that helps.
