### ISSUE TITLE
logout not implemented correctly

### ISSUE THREAD

**Issue by richardscholten73** [alexziskind1/nativescript-oauth2#68]
According to the oidc specification the end_session_endpoint should be called with the id token.
https://openid.net/specs/openid-connect-session-1_0.html#RPLogout

identityserver4 has implemented this as follows:
http://docs.identityserver.io/en/latest/endpoints/endsession.html#refendsession

But when the login method is called only the refresh token will be revoked on the revocation_endpoint, and the cookies and tokens are removed locally.

```
public logout() {
    this.callRevokeEndpoint();
    this.removeCookies();
    this.removeToken();
  }
```

```
public startTokenRevocation() {
    // call revoke token here
    const revokeUrl =
      this.client.provider.authority + this.client.provider.revokeEndpoint;
    const headers = {
      "Content-Type": "application/x-www-form-urlencoded"
    };
    const body = querystring.stringify({
      token: this.client.tokenResult.refreshToken
    });

    http
      .request({
        url: revokeUrl,
        method: "POST",
        headers: headers,
        content: body
      })
      .then(
        (response: http.HttpResponse) => {
          if (response.statusCode !== 200) {
            this.completion(
              null,
              response,
              new Error(`Failed logout with status ${response.statusCode}.`)
            );
          } else {
            this.completion(null, response, null);
          }
        },
        error => this.completion(null, null, error)
      );
  }
```

This means that a call to the login will result in new valid tokens without the need to fill in any credentials (For the provider you are still logged in)

This is not the expected/desired behaviour, as the end user will experience this as not being logged-out at all.
It also means that the end user cannot logout and then login as a different user.

**Comment by alexziskind1** [comment]
Thanks for the issue and the research, Richard. I appreciate any help on this and I would gladly review and accept PRs.

**Comment by richardscholten73** [comment]
@alexziskind1 We would like to participate but i cant get the project running.
Getting nothing but errors.

At the bottem of the readme you refer to the plugin page of nativescript: https://docs.nativescript.org/plugins/building-plugins
Not sure at what step we should start performing the mentioned commands.

Getting error at: (in src folder)
```
npm run postclone 

> nativescript-oauth2@2.1.1 postclone /Users/richards/repos/nativescript-oauth2/src
> npm i && node scripts/postclone.js && cd ../demo && npm i && npx rimraf -- package-lock.json && cd ../src

npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 0.473s
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/richards/repos/nativescript-oauth2/src/scripts/postclone.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-oauth2@2.1.1 postclone: `npm i && node scripts/postclone.js && cd ../demo && npm i && npx rimraf -- package-lock.json && cd ../src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nativescript-oauth2@2.1.1 postclone script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richards/.npm/_logs/2019-10-01T10_36_01_412Z-debug.log
```

Tried npm run demo.ios and npm run demo.android, but both give errors

```
npm run demo.android

> nativescript-oauth2@2.1.1 demo.android /Users/richards/repos/nativescript-oauth2/src
> npm run tsc && cd ../demo && tns run android --syncAllFiles --emulator


> nativescript-oauth2@2.1.1 tsc /Users/richards/repos/nativescript-oauth2/src
> tsc

The option 'syncAllFiles' is not supported. To see command's options, use '$ tns help run'. To see all commands use '$ tns help'.
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! nativescript-oauth2@2.1.1 demo.android: `npm run tsc && cd ../demo && tns run android --syncAllFiles --emulator`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nativescript-oauth2@2.1.1 demo.android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richards/.npm/_logs/2019-10-01T10_38_28_891Z-debug.log

```

We also tried to referense the library directly from code the same way the demo projects do.
In package.json:
`"nativescript-oauth2": "file:../nativescript-oauth2/src",`

Gives errors:

```
...
ERROR in /Users/richards/repos/nativescript-oauth2/src/oauth.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: /Users/richards/repos/nativescript-oauth2/src/oauth.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
...
```

Adding the location in the tsconfig.json did not solve the problem.

We tried everything we can think of in various combinations and orders, but we were unable to solve this.
Running out of options and pulling my hair out.

Could you helps us?
Maybe you can make a walkthrough that discribes the steps to get a fresh fork/clone demo (angular) working?

Kind regards,
Richard

**Comment by alexziskind1** [comment]
@richardscholten73 I've updated the README with the [Contributing Quick Steps](https://github.com/alexziskind1/nativescript-oauth2/blob/master/README.md#contributing-quick-steps).

**Comment by richardscholten73** [comment]
> @richardscholten73 I've updated the README with the [Contributing Quick Steps](https://github.com/alexziskind1/nativescript-oauth2/blob/master/README.md#contributing-quick-steps).

Thanks, we can now run the project.
Working on the logout, will make a pr when done.

**Comment by richardscholten73** [comment]
@alexziskind1 Ive pushed the changes to https://github.com/richardscholten73/nativescript-oauth2/tree/logout  and created a [pr](https://github.com/alexziskind1/nativescript-oauth2/pull/70 ) 

I added a provider for [https://identityserver.io/](https://identityserver.io/)
Made it the default for the angular demo app and configured it to use [https://demo.identityserver.io](https://demo.identityserver.io)
tested with:
```
npm run demo.android
```
and
```
npm run demo.ios
```
login with bob/bob or alice/alice

I am having difficulty understanding the callback mechanism, its not working as expected.
After the logout identityserver shows a page with a link to the given end_session_endpoint.
When clicked on android the demo app is re-opened, but the callback is not being invoked.
On ios nothing happens at all.
But when i close the browser (both ios and android) the callback is invoked and it works as expected.
Can't figure it out, any ideas?

Google does not support end_session_endpoint, did not check the other providers.
I will see if i can implement getLogoutUrlStr (simular as getAuthUrlStr) and use https://www.google.com/accounts/Logout for the google provider

Could u look at my pr?

Kind regards,
Richard

**Comment by alexziskind1** [comment]
Hi Richard, I really appreciate the PR! From your comment it looks like there needs to be more work done on it before it is in a working state - is that correct?

**Comment by richardscholten73** [comment]
> From your comment it looks like there needs to be more work done on it before it is in a working state - is that correct?

Not at the moment, this is it for now.
Maybe you could look at the callback?
For us this is fine and at least the logout is working according to specs on the identityserver provider.
So if you could evaluate the pr and merge it then that would be great!

**Comment by alexziskind1** [comment]
I've tested the identity server implementation and it works well (except the logout page link you mentioned). This is something we'll have to figure out, but for now, this is a good addition.
