### ISSUE TITLE
post_logout_redirect_uri doesn't work as expected

### ISSUE THREAD

**Issue by OkanEsen** [alexziskind1/nativescript-oauth2#78]
I think the issue #68 probably has something to do with it because of the comment from @richardscholten73:

> I am having difficulty understanding the callback mechanism, its not working as expected.
After the logout identityserver shows a page with a link to the given end_session_endpoint.
When clicked on android the demo app is re-opened, but the callback is not being invoked.

We're using the IdentityServer as our provider and configured it with `post_logout_redirect_uri` set to `org.nativescript.demoangular://auth` (same as `redirect_uri` which is set to the same value). Login works absolutely fine but as soon as we click the logout button and click the link inside the browser, to get back to our app, it just ends up on the logout page.

This doesn't seem surprising, since the `post_logout_redirect_uri` doesn't include any query parameters and the method call to `resumeWithUrl` [[0]](https://github.com/alexziskind1/nativescript-oauth2/blob/master/src/tns-oauth-login-sub-controller.ts#L75) with the parameter `org.nativescript.demoangular://auth` never resolves, since `codeExchangeRequestUrl` is null.

That's because the function call `codeExchangeWithUrlCompletion` [[1]](https://github.com/alexziskind1/nativescript-oauth2/blob/master/src/tns-oauth-login-sub-controller.ts#L80) returns null, since there is [no authorization code](https://github.com/alexziskind1/nativescript-oauth2/blob/master/src/tns-oauth-login-sub-controller.ts#L100) passed by the IdentityServer to the custom URL scheme.

In the end, the callback `completition` gets never resolved because, as stated before, `codeExchangeRequestUrl` is always, in the case of a logout, null [[2]](https://github.com/alexziskind1/nativescript-oauth2/blob/master/src/tns-oauth-login-sub-controller.ts#L84).

This kind of makes sense, since `codeExchangeWithUrlCompletion` [[3]](https://github.com/alexziskind1/nativescript-oauth2/blob/master/src/tns-oauth-login-sub-controller.ts#L112) looks like it was only made for the login routine, based on the name and definition of the method.

The question is, what would be the best way to solve this? Extend the plugin to listen to an additional URL custom scheme, like `org.nativescript.demoangular://auth-logout` and delegate it to a logout controller? Or do the check inside an auth guard by asking the IdentityServer, if the session is still valid?

Thank you very much for your hard work and have a great day!

**Comment by R4ZuL** [comment]
Hello OkanEsen,
i am struggeling with the same issue. Logout procedure does not work as expected. Hopefully we will find a solution.

Kind regards

RAZuL

**Comment by keithgulbro** [comment]
Hi everyone, any update on this? I'm attempting to use the logout method as well but unfortunately it isn't working.

**Comment by OkanEsen** [comment]
Should be fixed as of: #95
