### ISSUE TITLE
Do I need to use WebView with a custom provider?

### ISSUE THREAD

**Issue by aquinn637** [alexziskind1/nativescript-oauth2#79]
Question:

I’m writing an app with NativeScript & Angular 8. The app will work on Android & iOS.
I am considering putting Single Sign On technology into my app.

We will not be using the social methods to sign on such as Facebook, Google, etc. because we are writing an enterprise application for B2B purposes. Although, never say never.
We will be using Identity Provider & OpenID Connect.

I will get a URL from my backend server and display it in a browser so the customers can decide which SSO service they want to use. 

I thought about using this plugin to help with the SSO.

Do I need to use a WebView in my case since I am getting a custom URL from my server? If so, how do I use a WebView with this plugin? If not, how do I use this plugin in my case?

**Comment by alexziskind1** [comment]
I would suggest not using a webview and using the system browser auth approach instead. Take a look at the example with IdentityServer
