### ISSUE TITLE
Provider is not configured error

### ISSUE THREAD

**Issue by aquinn637** [alexziskind1/nativescript-oauth2#83]
I'm trying to play around with this plugin to get Google authentication working so I built a small prototype app based on the demo example. 

I'm working with Angular and Nativescript.

Here is my code: https://github.com/aquinn637/sso-google-test

I keep getting this error:
```
Successfully synced application org.nativescript.SSOGoogle on device 4d2bc6bf.
ActivityManager: Start proc org.nativescript.SSOGoogle for activity org.nativescript.SSOGoogle/com.tns.NativeScriptActivity: pid=25574 uid=10222 gids={50222, 9997, 1028, 1015, 3003} abi=armeabi-v7a
JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: back to main page with error:
JS: Provider is not configured
JS: Error: Provider is not configured
JS: back to main page with error:
JS: Provider is not configured
JS: Error: Provider is not configured
```

Do you know why I might be getting this error?

**Comment by alexziskind1** [comment]
Looks like your provider is not configured. Try the demo apps and see the code there to configure the provider.

**Comment by aquinn637** [comment]
@alexziskind1 I don't want to configure the other providers though. Only Google. How do I configure my provider?

**Comment by alexziskind1** [comment]
Just include the google one.

**Comment by alexziskind1** [comment]
Here is a video where I show this https://youtu.be/Ix0bXZeyhK0

**Comment by aquinn637** [comment]
@alexziskind1 I downloaded the demo project and I tried to build and there are many errors. 
Repos\nativescript-oauth2-master (1)\nativescript-oauth2-master\demo-angular>  
ERROR in ../src/delegate/delegate.android.ts(10,26): error TS2339: Property 'content' does not exist on type 'typeof android'.
../src/delegate/delegate.ios.ts(3,12): error TS2304: Cannot find name 'UIApplicationDelegate'.
../src/delegate/delegate.ios.ts(4,48): error TS2304: Cannot find name 'UIResponder'.
../src/delegate/delegate.ios.ts(5,14): error TS2304: Cannot find name 'UIApplicationDelegate'.
../src/delegate/delegate.ios.ts(16,18): error TS2304: Cannot find name 'UIApplication'.
../src/delegate/delegate.ios.ts(17,10): error TS2304: Cannot find name 'NSURL'.
../src/delegate/delegate.ios.ts(18,14): error TS2304: Cannot find name 'NSDictionary'.
../src/delegate/delegate.ios.ts(25,18): error TS2304: Cannot find name 'UIApplication'.
../src/delegate/delegate.ios.ts(26,10): error TS2304: Cannot find name 'NSURL'.
../src/delegate/delegate.ios.ts(33,34): error TS2304: Cannot find name 'NSURL'.
../src/delegate/delegate.ts(10,26): error TS2339: Property 'content' does not exist on type 'typeof android'.
../src/oauth.ts(110,9): error TS2304: Cannot find name 'NSHTTPCookieStorage'.
../src/oauth.ts(113,23): error TS2304: Cannot find name 'NSHTTPCookie'.
../src/oauth.ts(113,39): error TS2304: Cannot find name 'NSHTTPCookie'.
../src/oauth.ts(116,13): error TS2304: Cannot find name 'NSHTTPCookieStorage'.
../src/oauth.ts(121,25): error TS2304: Cannot find name 'WKWebsiteDataStore'.
../src/oauth.ts(123,9): error TS2304: Cannot find name 'WKWebsiteDataStore'.
../src/oauth.ts(125,30): error TS2304: Cannot find name 'WKWebsiteDataRecord'.
../src/oauth.ts(152,35): error TS2339: Property 'webkit' does not exist on type 'typeof android'.
../src/pkce-util.android.ts(2,45): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.android.ts(2,75): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.android.ts(2,108): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.android.ts(5,29): error TS2339: Property 'create' does not exist on type 'ArrayConstructor'.
../src/pkce-util.android.ts(6,7): error TS2304: Cannot find name 'java'.
../src/pkce-util.android.ts(7,18): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.android.ts(11,26): error TS2304: Cannot find name 'java'.
../src/pkce-util.android.ts(12,29): error TS2304: Cannot find name 'java'.
../src/pkce-util.android.ts(14,18): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.ios.ts(4,22): error TS2304: Cannot find name 'NSMutableData'.
../src/pkce-util.ios.ts(5,26): error TS2304: Cannot find name 'SecRandomCopyBytes'.
../src/pkce-util.ios.ts(5,45): error TS2304: Cannot find name 'kSecRandomDefault'.
../src/pkce-util.ios.ts(14,23): error TS2304: Cannot find name 'NSData'.
../src/pkce-util.ios.ts(14,32): error TS2304: Cannot find name 'NSString'.
../src/pkce-util.ios.ts(14,89): error TS2304: Cannot find name 'NSUTF8StringEncoding'.
../src/pkce-util.ios.ts(15,25): error TS2304: Cannot find name 'NSMutableData'.
../src/pkce-util.ios.ts(15,41): error TS2304: Cannot find name 'NSMutableData'.
../src/pkce-util.ios.ts(16,3): error TS2304: Cannot find name 'CC_SHA256'.
../src/pkce-util.ios.ts(20,41): error TS2304: Cannot find name 'NSData'.
../src/pkce-util.ts(2,45): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.ts(2,75): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.ts(2,108): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.ts(5,29): error TS2339: Property 'create' does not exist on type 'ArrayConstructor'.
../src/pkce-util.ts(6,7): error TS2304: Cannot find name 'java'.
../src/pkce-util.ts(7,18): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/pkce-util.ts(11,26): error TS2304: Cannot find name 'java'.
../src/pkce-util.ts(12,29): error TS2304: Cannot find name 'java'.
../src/pkce-util.ts(14,18): error TS2339: Property 'util' does not exist on type 'typeof android'.
../src/tns-oauth-native-view-controller.ios.ts(13,56): error TS2304: Cannot find name 'NSObject'.
../src/tns-oauth-native-view-controller.ios.ts(14,14): error TS2304: Cannot find name 'SFSafariViewControllerDelegate'.
../src/tns-oauth-native-view-controller.ios.ts(15,34): error TS2304: Cannot find name 'SFSafariViewControllerDelegate'.
../src/tns-oauth-native-view-controller.ios.ts(18,33): error TS2304: Cannot find name 'SFSafariViewController'.

**Comment by arnasdev** [comment]
Just to comment on this issue as I was experiencing the same thing, @aquinn637 the code you posted is almost correct except you specify "googleProvider" instead of "google". 

I came across this issue also and took me quite a while to identify the problem as I was typing "facebookProvider", it's written in the documentation but very easy to skip past!
