### ISSUE TITLE
LogoutWithCompletion Not Working

### ISSUE THREAD

**Issue by keithgulbro** [alexziskind1/nativescript-oauth2#94]
Hi everyone,

I'm currently implementing OAuth2 with Nativescript-Vue & encountering a minor issue. 

About a week ago I had no issues executing the `logoutWithCompletion` method however recently it seems that that method incorrectly redirects the WebView to an invalid logout URI. 

In my case, the 3rd party authentication is handled via Okta instead of Facebook or Google but even when testing the `logoutWithCompletion` method inside a valid Facebook authentication instance, the method still fails.

Here is a snippet of the URI that the WebView is attempting to load for logging out:

`https://dev-1234.okta.comundefined/?id_token_hint=...`

Any insight would be greatly appreciated

**Comment by Siafu** [comment]
I'm running into the same issue with Okta. How are you able to see the attempted URL?

**Comment by Siafu** [comment]
I'm using Okta and having the exact issue.

**Comment by keithgulbro** [comment]
@Siafu Since the maintainer of this plugin has been virtually no help, here's my basic workaround to the matter in Nativescript-Vue:

```
import * as application from "application";

    tnsOauthLogout() {
      let client = new nativescript_oauth2.TnsOAuthClient("okta");
      // Assign client properties used to identify the actively authenticated session
      // Save these variables from the oAuth client in VueX
      client.tokenResult = this.oktaClientTokenResult; 
      client.codeVerifier = this.oktaClientCodeVerifier;

      client.logoutWithCompletion((result, err) => {
        if (result) {
          console.log(result);
        } else {
          console.log(err);
        }
      });

      setTimeout(() => {
        if (application.ios) {
          // Required to logout iOS because the Logout route redirects to an "Undefined" (blank) page instead of the login URL
          const controller =
            application.ios.nativeApp.windows[0].rootViewController;

          controller.dismissViewControllerAnimatedCompletion(true, () => {
            console.log("Safari dismissed");
          });
          this.tnsOauthLogin("okta");
        } else {
          this.tnsOauthLogin("okta");
        }
      }, 2000);
    },
```

Please feel free to hit me up if you have any questions.

**Comment by alexziskind1** [comment]
Thanks for posting that @keithgulbro ! 
On a secondary note. I'm looking for help maintaining this plugin. If you're up for it, let me know.

**Comment by SmailHammour** [comment]
I'm also getting this error with a custom provider. Any help?

**Comment by keithgulbro** [comment]
@SmailHammour Is you issue on both platforms or isolated?

Please also provide details inside your package.json file so we can get a better understanding of your current project stack. Thanks!

**Comment by tapirs** [comment]
Hi, I came across this when I was having the same issue, I managed to get it working without the workaround. 

I found the getLogoutUrlStr function in tns-oauth-utils which uses this constructed URL to call the logout endpoint

`provider.authority + provider.endSessionEndpoint + "?" + pararmsStr;`

I set `endSessionEndpoint = '/oauth2/xxxxxxxxxx/v1/logout'` and that picked up the correct URL rather than `undefined`.
